### ISSUE TITLE
Crash on blueprint fill and curved rail

### ISSUE THREAD

**Issue by StephanSteinert** [keryja/factorio-fast-filter-fill#4]
2168.108 Error MainLoop.cpp:1016: Exception at tick 223194: Error while running event fast-filter-fill::on_gui_click (ID 1)
Unknown item name: curved-rail
stack traceback:
	__fast-filter-fill__/control.lua:275: in function 'handler'
	__fast-filter-fill__/control.lua:23: in function <__fast-filter-fill__/control.lua:20>

Curved rail consists of 4 straight rails. But do we need to add a hardcoded workaround for this item or can we receive some information from the entity?

Edit: http://lua-api.factorio.com/latest/LuaEntityPrototype.html#LuaEntityPrototype.items_to_place_this should work.

**Comment by keryja** [comment]
Fixed in 0.6.6, thanks for reporting!
