### ISSUE TITLE
On gui opened bug

### ISSUE THREAD

**Issue by Jelmergu** [keryja/factorio-fast-filter-fill#6]
I don't know exactly what we did, but during a multiplayer game an error.
I have attached an image of the error and the savegame itself to the report report
![error on_gui_opened](https://user-images.githubusercontent.com/18192158/39576836-d6663b42-4edf-11e8-986f-23b559e73d6d.png)
[error_on_gui_opened.zip](https://github.com/keryja/factorio-fast-filter-fill/files/1970855/error_on_gui_opened.zip)

**Comment by keryja** [comment]
The error occurs when something is opened, what did you open at the time? It would help with testing a fix. Thanks!

**Comment by Jelmergu** [comment]
I opened my characters inventory. What my multiplayer partner opened I don't know
I am prepared to try it out with you in the same multiplayer server if you'd want.

**Comment by keryja** [comment]
I've uploaded a new version of the mod that should fix things, let me know if you still have issues.

**Comment by Jelmergu** [comment]
Will do

**Comment by keryja** [comment]
We were checking for the `get_output_inventory()` method on `player.opened`, unfortunately Factorio's table class throws an error when accessing a key that doesn't exist. Instead of that we now check if `player.opened` is a LuaEntity which will always have the `get_output_inventory()` method.

**Comment by Jelmergu** [comment]
Yeah, that error throwing is a problem I am familiar with...

**Comment by keryja** [comment]
Considering this fixed
